/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/grb/repos/TreeHouse-Private/TreeHouse/pql.g
 *     -                            On : 2013-06-18 14:27:22
 *     -                 for the lexer : pqlLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The lexer 
pqlLexer

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef ppqlLexer, which is returned from a call to pqlLexerNew().
 *
 * As this is a generated lexer, it is unlikely you will call it 'manually'. However
 * the methods are provided anyway.
 *
 * The methods in ppqlLexer are  as follows:
 *
 *  - 
 void
      ppqlLexer->T__17(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__18(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__19(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__20(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__21(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__22(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__23(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__24(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__25(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__26(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__27(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__28(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__29(ppqlLexer)
 *  - 
 void
      ppqlLexer->T__30(ppqlLexer)
 *  - 
 void
      ppqlLexer->IDENTIFIER(ppqlLexer)
 *  - 
 void
      ppqlLexer->LETTER(ppqlLexer)
 *  - 
 void
      ppqlLexer->CHARACTER_LITERAL(ppqlLexer)
 *  - 
 void
      ppqlLexer->STRING_LITERAL(ppqlLexer)
 *  - 
 void
      ppqlLexer->STRING_GUTS(ppqlLexer)
 *  - 
 void
      ppqlLexer->RANGE_LITERAL(ppqlLexer)
 *  - 
 void
      ppqlLexer->DECIMAL_LITERAL(ppqlLexer)
 *  - 
 void
      ppqlLexer->FLOATING_POINT_LITERAL(ppqlLexer)
 *  - 
 void
      ppqlLexer->EscapeSequence(ppqlLexer)
 *  - 
 void
      ppqlLexer->COMMENT(ppqlLexer)
 *  - 
 void
      ppqlLexer->LINE_COMMENT(ppqlLexer)
 *  - 
 void
      ppqlLexer->NEWLINE(ppqlLexer)
 *  - 
 void
      ppqlLexer->WS(ppqlLexer)
 *  - 
 void
      ppqlLexer->Tokens(ppqlLexer)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_pqlLexer_H
#define _pqlLexer_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct pqlLexer_Ctx_struct pqlLexer, * ppqlLexer;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
pqlLexer

 */
struct pqlLexer_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_LEXER    pLexer;

     void
     (*mT__17)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__18)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__19)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__20)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__21)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__22)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__23)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__24)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__25)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__26)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__27)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__28)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__29)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mT__30)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mIDENTIFIER)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mLETTER)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mCHARACTER_LITERAL)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mSTRING_LITERAL)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mSTRING_GUTS)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mRANGE_LITERAL)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mDECIMAL_LITERAL)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mFLOATING_POINT_LITERAL)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mEscapeSequence)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mCOMMENT)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mLINE_COMMENT)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mNEWLINE)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mWS)	(struct pqlLexer_Ctx_struct * ctx);

     void
     (*mTokens)	(struct pqlLexer_Ctx_struct * ctx);
    const char * (*getGrammarFileName)();
    void            (*reset)  (struct pqlLexer_Ctx_struct * ctx);
    void	    (*free)   (struct pqlLexer_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API ppqlLexer pqlLexerNew         (
pANTLR3_INPUT_STREAM
 instream);
ANTLR3_API ppqlLexer pqlLexerNewSSD      (
pANTLR3_INPUT_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
lexer
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define CHARACTER_LITERAL      4
#define COMMENT      5
#define DECIMAL_LITERAL      6
#define EscapeSequence      7
#define FLOATING_POINT_LITERAL      8
#define IDENTIFIER      9
#define LETTER      10
#define LINE_COMMENT      11
#define NEWLINE      12
#define RANGE_LITERAL      13
#define STRING_GUTS      14
#define STRING_LITERAL      15
#define WS      16
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for pqlLexer
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
