/** \file
 *  This C source file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/jaholtz/Treehouse-Private/TreeHouse/pql.g
 *     -                            On : 2013-07-23 15:55:33
 *     -                 for the lexer : pqlLexerLexer
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
*/
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

/* -----------------------------------------
 * Include the ANTLR3 generated header file.
 */
#include    "pqlLexer.h"
/* ----------------------------------------- */


/** String literals used by pqlLexer that we must do things like MATCHS() with.
 *  C will normally just lay down 8 bit characters, and you can use L"xxx" to
 *  get wchar_t, but wchar_t is 16 bits on Windows, which is not UTF32 and so
 *  we perform this little trick of defining the literals as arrays of UINT32
 *  and passing in the address of these.
 */
static ANTLR3_UCHAR	lit_1[]  = { 0x21, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_2[]  = { 0x3D, 0x3D,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_3[]  = { 0x2E, 0x2E,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_4[]  = { 0x2F, 0x2A,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_5[]  = { 0x2A, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_6[]  = { 0x2F, 0x2F,  ANTLR3_STRING_TERMINATOR};
static ANTLR3_UCHAR	lit_7[]  = { 0x0D, 0x0A,  ANTLR3_STRING_TERMINATOR};





/* MACROS that hide the C interface implementations from the
 * generated code, which makes it a little more understandable to the human eye.
 * I am very much against using C pre-processor macros for function calls and bits
 * of code as you cannot see what is happening when single stepping in debuggers
 * and so on. The exception (in my book at least) is for generated code, where you are
 * not maintaining it, but may wish to read and understand it. If you single step it, you know that input()
 * hides some indirect calls, but is always referring to the input stream. This is
 * probably more readable than ctx->input->istream->input(snarfle0->blarg) and allows me to rejig
 * the runtime interfaces without changing the generated code too often, without
 * confusing the reader of the generated output, who may not wish to know the gory
 * details of the interface inheritance.
 */

#define		CTX	ctx

/* Aids in accessing scopes for grammar programmers
 */
#undef	SCOPE_TYPE
#undef	SCOPE_STACK
#undef	SCOPE_TOP
#define	SCOPE_TYPE(scope)   ppqlLexer_##scope##_SCOPE
#define SCOPE_STACK(scope)  ppqlLexer_##scope##Stack
#define	SCOPE_TOP(scope)    ctx->ppqlLexer_##scope##Top
#define	SCOPE_SIZE(scope)		ctx->ppqlLexer_##scope##Stack_limit
#define SCOPE_INSTANCE(scope, i)	(ctx->SCOPE_STACK(scope)->get(ctx->SCOPE_STACK(scope),i))


/* Macros for accessing things in a lexer
 */
#undef	    LEXER
#undef	    RECOGNIZER
#undef	    RULEMEMO
#undef	    GETCHARINDEX
#undef	    GETLINE
#undef	    GETCHARPOSITIONINLINE
#undef	    EMIT
#undef	    EMITNEW
#undef	    MATCHC
#undef	    MATCHS
#undef	    MATCHRANGE
#undef	    LTOKEN
#undef	    HASFAILED
#undef	    FAILEDFLAG
#undef	    INPUT
#undef	    STRSTREAM
#undef	    LA
#undef	    HASEXCEPTION
#undef	    EXCEPTION
#undef	    CONSTRUCTEX
#undef	    CONSUME
#undef	    LRECOVER
#undef	    MARK
#undef	    REWIND
#undef	    REWINDLAST
#undef	    BACKTRACKING
#undef		MATCHANY
#undef		MEMOIZE
#undef		HAVEPARSEDRULE
#undef		GETTEXT
#undef		INDEX
#undef		SEEK
#undef		PUSHSTREAM
#undef		POPSTREAM
#undef		SETTEXT
#undef		SETTEXT8

#define	    LEXER					ctx->pLexer
#define	    RECOGNIZER			    LEXER->rec
#define		LEXSTATE				RECOGNIZER->state
#define		TOKSOURCE				LEXSTATE->tokSource
#define	    GETCHARINDEX()			LEXER->getCharIndex(LEXER)
#define	    GETLINE()				LEXER->getLine(LEXER)
#define	    GETTEXT()				LEXER->getText(LEXER)
#define	    GETCHARPOSITIONINLINE() LEXER->getCharPositionInLine(LEXER)
#define	    EMIT()					LEXSTATE->type = _type; LEXER->emit(LEXER)
#define	    EMITNEW(t)				LEXER->emitNew(LEXER, t)
#define	    MATCHC(c)				LEXER->matchc(LEXER, c)
#define	    MATCHS(s)				LEXER->matchs(LEXER, s)
#define	    MATCHRANGE(c1,c2)	    LEXER->matchRange(LEXER, c1, c2)
#define	    MATCHANY()				LEXER->matchAny(LEXER)
#define	    LTOKEN  				LEXSTATE->token
#define	    HASFAILED()				(LEXSTATE->failed == ANTLR3_TRUE)
#define	    BACKTRACKING			LEXSTATE->backtracking
#define	    FAILEDFLAG				LEXSTATE->failed
#define	    INPUT					LEXER->input
#define	    STRSTREAM				INPUT
#define		ISTREAM					INPUT->istream
#define		INDEX()					ISTREAM->index(ISTREAM)
#define		SEEK(n)					ISTREAM->seek(ISTREAM, n)
#define	    EOF_TOKEN				&(LEXSTATE->tokSource->eofToken)
#define	    HASEXCEPTION()			(LEXSTATE->error == ANTLR3_TRUE)
#define	    EXCEPTION				LEXSTATE->exception
#define	    CONSTRUCTEX()			RECOGNIZER->exConstruct(RECOGNIZER)
#define	    LRECOVER()				LEXER->recover(LEXER)
#define	    MARK()					ISTREAM->mark(ISTREAM)
#define	    REWIND(m)				ISTREAM->rewind(ISTREAM, m)
#define	    REWINDLAST()			ISTREAM->rewindLast(ISTREAM)
#define		MEMOIZE(ri,si)			RECOGNIZER->memoize(RECOGNIZER, ri, si)
#define		HAVEPARSEDRULE(r)		RECOGNIZER->alreadyParsedRule(RECOGNIZER, r)
#define		PUSHSTREAM(str)			LEXER->pushCharStream(LEXER, str)
#define		POPSTREAM()				LEXER->popCharStream(LEXER)
#define		SETTEXT(str)			LEXSTATE->text = str
#define		SKIP()					LEXSTATE->token = &(TOKSOURCE->skipToken)
#define		USER1					LEXSTATE->user1
#define		USER2					LEXSTATE->user2
#define		USER3					LEXSTATE->user3
#define		CUSTOM					LEXSTATE->custom
#define		RULEMEMO				LEXSTATE->ruleMemo
#define		DBG						RECOGNIZER->debugger

/* If we have been told we can rely on the standard 8 bit or UTF16 input
 * stream, then we can define our macros to use the direct pointers
 * in the input object, which is much faster than indirect calls. This
 * is really only significant to lexers with a lot of fragment rules (which
 * do not place LA(1) in a temporary at the moment) and even then
 * only if there is a lot of input (order of say 1M or so).
 */
#if	defined(ANTLR3_INLINE_INPUT_8BIT) || defined(ANTLR3_INLINE_INPUT_UTF16)

# ifdef	ANTLR3_INLINE_INPUT_8BIT

/* 8 bit character set */

#  define	    NEXTCHAR	((pANTLR3_UINT8)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT8)(INPUT->data))

# else

#  define	    NEXTCHAR	((pANTLR3_UINT16)(INPUT->nextChar))
#  define	    DATAP	((pANTLR3_UINT16)(INPUT->data))

# endif

# define	    LA(n) ((NEXTCHAR + n) > (DATAP + INPUT->sizeBuf) ? ANTLR3_CHARSTREAM_EOF : (ANTLR3_UCHAR)(*(NEXTCHAR + n - 1)))
# define            CONSUME()                                           \
{                                                                       \
    if        (NEXTCHAR < (DATAP + INPUT->sizeBuf))                     \
    {                                                                   \
        INPUT->charPositionInLine++;                                    \
        if  ((ANTLR3_UCHAR)(*NEXTCHAR) == INPUT->newlineChar)           \
        {                                                               \
            INPUT->line++;                                              \
            INPUT->charPositionInLine        = 0;                       \
            INPUT->currentLine                = (void *)(NEXTCHAR + 1); \
        }                                                               \
        INPUT->nextChar = (void *)(NEXTCHAR + 1);                       \
    }                                                                   \
}

#else

// Pick up the input character by calling the input stream implementation.
//
#define	    CONSUME()   INPUT->istream->consume(INPUT->istream)
#define	    LA(n)       INPUT->istream->_LA(INPUT->istream, n)

#endif

#define		TOKTEXT(tok, txt)				tok, (pANTLR3_UINT8)txt

/* The 4 tokens defined below may well clash with your own #defines or token types. If so
 * then for the present you must use different names for your defines as these are hard coded
 * in the code generator. It would be better not to use such names internally, and maybe
 * we can change this in a forthcoming release. I deliberately do not #undef these
 * here as this will at least give you a redefined error somewhere if they clash.
 */
#define	    UP	    ANTLR3_TOKEN_UP
#define	    DOWN    ANTLR3_TOKEN_DOWN
#define	    EOR	    ANTLR3_TOKEN_EOR
#define	    INVALID ANTLR3_TOKEN_INVALID


/* =============================================================================
 * Functions to create and destroy scopes. First come the rule scopes, followed
 * by the global declared scopes.
 */



/* ============================================================================= */

/* =============================================================================
 * Start of recognizer
 */

/* Forward declare the locally static matching functions we have generated and any predicate functions.
 */
static ANTLR3_INLINE 
 void
	mT__17    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__18    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__19    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__20    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__21    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__22    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__23    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__24    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__25    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__26    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__27    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__28    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__29    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mT__30    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mIDENTIFIER    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mLETTER    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mCHARACTER_LITERAL    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_LITERAL    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mSTRING_GUTS    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mRANGE_LITERAL    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mDECIMAL_LITERAL    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mFLOATING_POINT_LITERAL    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mEscapeSequence    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mCOMMENT    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mLINE_COMMENT    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mNEWLINE    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mWS    (ppqlLexer ctx);
static ANTLR3_INLINE 
 void
	mTokens    (ppqlLexer ctx);
static void	pqlLexerFree(ppqlLexer ctx);

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */



static void
pqlLexerFree  (ppqlLexer ctx)
{
    LEXER->free(LEXER);

    ANTLR3_FREE(ctx);
}

static void
pqlLexerReset (ppqlLexer ctx)
{
    RECOGNIZER->reset(RECOGNIZER);
}

/** \brief Name of the grammar file that generated this code
 */
static const char fileName[] = "/home/jaholtz/Treehouse-Private/TreeHouse/pql.g";

/** \brief Return the name of the grammar file that generated this code.
 */
static const char * getGrammarFileName()
{
	return fileName;
}

/** \brief Create a new lexer called pqlLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \return
 *     - Success ppqlLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API ppqlLexer pqlLexerNew
(
pANTLR3_INPUT_STREAM
 instream)
{
	// See if we can create a new lexer with the standard constructor
	//
	return pqlLexerNewSSD(instream, NULL);
}

/** \brief Create a new lexer called pqlLexer
 *
 * \param[in]    instream Pointer to an initialized input stream
 * \param[state] state Previously created shared recognizer stat
 * \return
 *     - Success ppqlLexer initialized for the lex start
 *     - Fail NULL
 */
ANTLR3_API ppqlLexer pqlLexerNewSSD
(pANTLR3_INPUT_STREAM instream, pANTLR3_RECOGNIZER_SHARED_STATE state)
{
    ppqlLexer ctx; // Context structure we will build and return

    ctx = (ppqlLexer) ANTLR3_CALLOC(1, sizeof(pqlLexer));

    if  (ctx == NULL)
    {
        // Failed to allocate memory for lexer context
        return  NULL;
    }

    /* -------------------------------------------------------------------
     * Memory for basic structure is allocated, now to fill in
     * in base ANTLR3 structures. We initialize the function pointers
     * for the standard ANTLR3 lexer function set, but upon return
     * from here, the programmer may set the pointers to provide custom
     * implementations of each function.
     *
     * We don't use the macros defined in pqlLexer.h here so you can get a sense
     * of what goes where.
     */

    /* Create a base lexer, using the supplied input stream
     */
    ctx->pLexer	= antlr3LexerNewStream(ANTLR3_SIZE_HINT, instream, state);

    /* Check that we allocated the memory correctly
     */
    if	(ctx->pLexer == NULL)
    {
		ANTLR3_FREE(ctx);
		return  NULL;
    }
    /* Install the implementation of our pqlLexer interface
     */
    ctx->mT__17	= mT__17;
    ctx->mT__18	= mT__18;
    ctx->mT__19	= mT__19;
    ctx->mT__20	= mT__20;
    ctx->mT__21	= mT__21;
    ctx->mT__22	= mT__22;
    ctx->mT__23	= mT__23;
    ctx->mT__24	= mT__24;
    ctx->mT__25	= mT__25;
    ctx->mT__26	= mT__26;
    ctx->mT__27	= mT__27;
    ctx->mT__28	= mT__28;
    ctx->mT__29	= mT__29;
    ctx->mT__30	= mT__30;
    ctx->mIDENTIFIER	= mIDENTIFIER;
    ctx->mLETTER	= mLETTER;
    ctx->mCHARACTER_LITERAL	= mCHARACTER_LITERAL;
    ctx->mSTRING_LITERAL	= mSTRING_LITERAL;
    ctx->mSTRING_GUTS	= mSTRING_GUTS;
    ctx->mRANGE_LITERAL	= mRANGE_LITERAL;
    ctx->mDECIMAL_LITERAL	= mDECIMAL_LITERAL;
    ctx->mFLOATING_POINT_LITERAL	= mFLOATING_POINT_LITERAL;
    ctx->mEscapeSequence	= mEscapeSequence;
    ctx->mCOMMENT	= mCOMMENT;
    ctx->mLINE_COMMENT	= mLINE_COMMENT;
    ctx->mNEWLINE	= mNEWLINE;
    ctx->mWS	= mWS;
    ctx->mTokens	= mTokens;

    /** When the nextToken() call is made to this lexer's pANTLR3_TOKEN_SOURCE
     *  it will call mTokens() in this generated code, and will pass it the ctx
     * pointer of this lexer, not the context of the base lexer, so store that now.
     */
    ctx->pLexer->ctx	    = ctx;

    /**Install the token matching function
     */
    ctx->pLexer->mTokens = (void (*) (void *))(mTokens);

    ctx->getGrammarFileName	= getGrammarFileName;
    ctx->free		= pqlLexerFree;
    ctx->reset          = pqlLexerReset;


    /* Return the newly built lexer to the caller
     */
    return  ctx;
}

/* =========================================================================
 * DFA tables for the lexer
 */
/** Static dfa state tables for Cyclic dfa:
 *    1:1: Tokens : ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | IDENTIFIER | CHARACTER_LITERAL | STRING_LITERAL | RANGE_LITERAL | DECIMAL_LITERAL | FLOATING_POINT_LITERAL | COMMENT | LINE_COMMENT | NEWLINE | WS );
 */
static const ANTLR3_INT32 dfa19_eot[36] =
    {
	-1, 24, -1, -1, -1, -1, 25, 28, -1, -1, -1, -1, -1, -1, -1, -1, 30, 30, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 18, -1, 30, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa19_eof[36] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa19_min[36] =
    {
	9, 61, -1, -1, -1, -1, 48, 61, -1, -1, -1, -1, -1, -1, -1, -1, 46, 46, 
	-1, 42, -1, -1, -1, -1, -1, -1, 46, -1, -1, 46, -1, 46, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa19_max[36] =
    {
	125, 61, -1, -1, -1, -1, 57, 61, -1, -1, -1, -1, -1, -1, -1, -1, 57, 57, 
	-1, 47, -1, -1, -1, -1, -1, -1, 57, -1, -1, 46, -1, 57, -1, -1, -1, -1
    };
static const ANTLR3_INT32 dfa19_accept[36] =
    {
	-1, -1, 3, 4, 5, 6, -1, -1, 10, 11, 12, 13, 14, 15, 16, 17, -1, -1, 20, 
	-1, 23, 23, 24, 2, 1, 7, -1, 9, 8, -1, 19, -1, 21, 22, 23, 18
    };
static const ANTLR3_INT32 dfa19_special[36] =
    {
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1
    };

/** Used when there is no transition table entry for a particular state */
#define dfa19_T_empty	    NULL

static const ANTLR3_INT32 dfa19_T0[] =
    {
	29, -1, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31
    };

static const ANTLR3_INT32 dfa19_T1[] =
    {
	29, -1, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26
    };

static const ANTLR3_INT32 dfa19_T2[] =
    {
	23
    };

static const ANTLR3_INT32 dfa19_T3[] =
    {
	27
    };

static const ANTLR3_INT32 dfa19_T4[] =
    {
	32, -1, -1, -1, -1, 33
    };

static const ANTLR3_INT32 dfa19_T5[] =
    {
	22, 21, -1, 22, 20, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
	-1, -1, -1, -1, -1, 22, 1, 15, -1, 13, -1, -1, 14, 2, 3, -1, 4, 5, 6, 18, 
	19, 16, 17, 17, 17, 17, 17, 17, 17, 17, 17, -1, -1, -1, 7, -1, -1, -1, 
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
	13, 13, 13, 13, 13, 13, 13, 13, 8, -1, 9, 10, 13, -1, 13, 13, 13, 13, 13, 
	13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 
	13, 13, 13, 11, -1, 12
    };

static const ANTLR3_INT32 dfa19_T6[] =
    {
	35
    };

static const ANTLR3_INT32 dfa19_T7[] =
    {
	26, 17, 17, 17, 17, 17, 17, 17, 17, 17
    };


/* Transition tables are a table of sub tables, with some tables
 * reused for efficiency.
 */
static const ANTLR3_INT32 * const dfa19_transitions[] =
{
    dfa19_T5, dfa19_T2, NULL, NULL, NULL, NULL, dfa19_T7, dfa19_T3, NULL, 
    NULL, NULL, NULL, NULL, NULL, NULL, NULL, dfa19_T1, dfa19_T0, NULL, 
    dfa19_T4, NULL, NULL, NULL, NULL, NULL, NULL, dfa19_T1, NULL, NULL, 
    dfa19_T6, NULL, dfa19_T0, NULL, NULL, NULL, NULL
};


/* Declare tracking structure for Cyclic DFA 19
 */
static
ANTLR3_CYCLIC_DFA cdfa19
    =	{
	    19,		    /* Decision number of this dfa	    */
	    /* Which decision this represents:   */
	    (const pANTLR3_UCHAR)"1:1: Tokens : ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | IDENTIFIER | CHARACTER_LITERAL | STRING_LITERAL | RANGE_LITERAL | DECIMAL_LITERAL | FLOATING_POINT_LITERAL | COMMENT | LINE_COMMENT | NEWLINE | WS );",
	    (CDFA_SPECIAL_FUNC) antlr3dfaspecialStateTransition,	/* Default special state transition function	*/

	    antlr3dfaspecialTransition,		/* DFA specialTransition is currently just a default function in the runtime */
	    antlr3dfapredict,			/* DFA simulator function is in the runtime */
	    dfa19_eot,	    /* EOT table			    */
	    dfa19_eof,	    /* EOF table			    */
	    dfa19_min,	    /* Minimum tokens for each state    */
	    dfa19_max,	    /* Maximum tokens for each state    */
	    dfa19_accept,	/* Accept table			    */
	    dfa19_special,	/* Special transition states	    */
	    dfa19_transitions	/* Table of transition tables	    */

	};
/* End of Cyclic DFA 19
 * ---------------------
 */ 
/* =========================================================================
 * End of DFA tables for the lexer
 */

/* =========================================================================
 * Functions to match the lexer grammar defined tokens from the input stream
 */

//   Comes from: 7:7: ( '!' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__17
 *
 * Looks to match the characters the constitute the token T__17
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__17(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__17;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:7:7: ( '!' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:7:9: '!'
    {
        MATCHC('!');
        if  (HASEXCEPTION())
        {
            goto ruleT__17Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__17Ex; /* Prevent compiler warnings */
    ruleT__17Ex: ;

}
// $ANTLR end T__17

//   Comes from: 8:7: ( '!=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__18
 *
 * Looks to match the characters the constitute the token T__18
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__18(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__18;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:8:7: ( '!=' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:8:9: '!='
    {
        MATCHS(lit_1);
        if  (HASEXCEPTION())
        {
            goto ruleT__18Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__18Ex; /* Prevent compiler warnings */
    ruleT__18Ex: ;

}
// $ANTLR end T__18

//   Comes from: 9:7: ( '(' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__19
 *
 * Looks to match the characters the constitute the token T__19
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__19(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__19;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:9:7: ( '(' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:9:9: '('
    {
        MATCHC('(');
        if  (HASEXCEPTION())
        {
            goto ruleT__19Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__19Ex; /* Prevent compiler warnings */
    ruleT__19Ex: ;

}
// $ANTLR end T__19

//   Comes from: 10:7: ( ')' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__20
 *
 * Looks to match the characters the constitute the token T__20
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__20(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__20;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:10:7: ( ')' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:10:9: ')'
    {
        MATCHC(')');
        if  (HASEXCEPTION())
        {
            goto ruleT__20Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__20Ex; /* Prevent compiler warnings */
    ruleT__20Ex: ;

}
// $ANTLR end T__20

//   Comes from: 11:7: ( '+' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__21
 *
 * Looks to match the characters the constitute the token T__21
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__21(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__21;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:11:7: ( '+' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:11:9: '+'
    {
        MATCHC('+');
        if  (HASEXCEPTION())
        {
            goto ruleT__21Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__21Ex; /* Prevent compiler warnings */
    ruleT__21Ex: ;

}
// $ANTLR end T__21

//   Comes from: 12:7: ( ',' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__22
 *
 * Looks to match the characters the constitute the token T__22
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__22(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__22;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:12:7: ( ',' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:12:9: ','
    {
        MATCHC(',');
        if  (HASEXCEPTION())
        {
            goto ruleT__22Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__22Ex; /* Prevent compiler warnings */
    ruleT__22Ex: ;

}
// $ANTLR end T__22

//   Comes from: 13:7: ( '-' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__23
 *
 * Looks to match the characters the constitute the token T__23
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__23(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__23;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:13:7: ( '-' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:13:9: '-'
    {
        MATCHC('-');
        if  (HASEXCEPTION())
        {
            goto ruleT__23Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__23Ex; /* Prevent compiler warnings */
    ruleT__23Ex: ;

}
// $ANTLR end T__23

//   Comes from: 14:7: ( '=' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__24
 *
 * Looks to match the characters the constitute the token T__24
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__24(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__24;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:14:7: ( '=' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:14:9: '='
    {
        MATCHC('=');
        if  (HASEXCEPTION())
        {
            goto ruleT__24Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__24Ex; /* Prevent compiler warnings */
    ruleT__24Ex: ;

}
// $ANTLR end T__24

//   Comes from: 15:7: ( '==' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__25
 *
 * Looks to match the characters the constitute the token T__25
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__25(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__25;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:15:7: ( '==' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:15:9: '=='
    {
        MATCHS(lit_2);
        if  (HASEXCEPTION())
        {
            goto ruleT__25Ex;
        }




    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__25Ex; /* Prevent compiler warnings */
    ruleT__25Ex: ;

}
// $ANTLR end T__25

//   Comes from: 16:7: ( '[' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__26
 *
 * Looks to match the characters the constitute the token T__26
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__26(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__26;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:16:7: ( '[' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:16:9: '['
    {
        MATCHC('[');
        if  (HASEXCEPTION())
        {
            goto ruleT__26Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__26Ex; /* Prevent compiler warnings */
    ruleT__26Ex: ;

}
// $ANTLR end T__26

//   Comes from: 17:7: ( ']' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__27
 *
 * Looks to match the characters the constitute the token T__27
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__27(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__27;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:17:7: ( ']' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:17:9: ']'
    {
        MATCHC(']');
        if  (HASEXCEPTION())
        {
            goto ruleT__27Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__27Ex; /* Prevent compiler warnings */
    ruleT__27Ex: ;

}
// $ANTLR end T__27

//   Comes from: 18:7: ( '^' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__28
 *
 * Looks to match the characters the constitute the token T__28
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__28(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__28;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:18:7: ( '^' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:18:9: '^'
    {
        MATCHC('^');
        if  (HASEXCEPTION())
        {
            goto ruleT__28Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__28Ex; /* Prevent compiler warnings */
    ruleT__28Ex: ;

}
// $ANTLR end T__28

//   Comes from: 19:7: ( '{' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__29
 *
 * Looks to match the characters the constitute the token T__29
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__29(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__29;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:19:7: ( '{' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:19:9: '{'
    {
        MATCHC('{');
        if  (HASEXCEPTION())
        {
            goto ruleT__29Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__29Ex; /* Prevent compiler warnings */
    ruleT__29Ex: ;

}
// $ANTLR end T__29

//   Comes from: 20:7: ( '}' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start T__30
 *
 * Looks to match the characters the constitute the token T__30
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mT__30(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = T__30;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:20:7: ( '}' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:20:9: '}'
    {
        MATCHC('}');
        if  (HASEXCEPTION())
        {
            goto ruleT__30Ex;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleT__30Ex; /* Prevent compiler warnings */
    ruleT__30Ex: ;

}
// $ANTLR end T__30

//   Comes from: 635:5: ( LETTER ( LETTER | '0' .. '9' )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start IDENTIFIER
 *
 * Looks to match the characters the constitute the token IDENTIFIER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mIDENTIFIER(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = IDENTIFIER;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:635:5: ( LETTER ( LETTER | '0' .. '9' )* )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:635:8: LETTER ( LETTER | '0' .. '9' )*
    {
        /* 635:8: LETTER ( LETTER | '0' .. '9' )* */
        mLETTER(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleIDENTIFIEREx;
        }



        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:635:15: ( LETTER | '0' .. '9' )*

        for (;;)
        {
            int alt1=2;
            switch ( LA(1) )
            {
            case '$':
            case '0':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case 'A':
            case 'B':
            case 'C':
            case 'D':
            case 'E':
            case 'F':
            case 'G':
            case 'H':
            case 'I':
            case 'J':
            case 'K':
            case 'L':
            case 'M':
            case 'N':
            case 'O':
            case 'P':
            case 'Q':
            case 'R':
            case 'S':
            case 'T':
            case 'U':
            case 'V':
            case 'W':
            case 'X':
            case 'Y':
            case 'Z':
            case '_':
            case 'a':
            case 'b':
            case 'c':
            case 'd':
            case 'e':
            case 'f':
            case 'g':
            case 'h':
            case 'i':
            case 'j':
            case 'k':
            case 'l':
            case 'm':
            case 'n':
            case 'o':
            case 'p':
            case 'q':
            case 'r':
            case 's':
            case 't':
            case 'u':
            case 'v':
            case 'w':
            case 'x':
            case 'y':
            case 'z':
            	{
            		alt1=1;
            	}
                break;

            }

            switch (alt1)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
        	    {
        	        if ( LA(1) == '$' || ((LA(1) >= '0') && (LA(1) <= '9')) || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleIDENTIFIEREx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop1;	/* break out of the loop */
        	    break;
            }
        }
        loop1: ; /* Jump out to here if this rule does not match */


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleIDENTIFIEREx; /* Prevent compiler warnings */
    ruleIDENTIFIEREx: ;

}
// $ANTLR end IDENTIFIER

//   Comes from: 641:5: ( '$' | 'A' .. 'Z' | 'a' .. 'z' | '_' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LETTER
 *
 * Looks to match the characters the constitute the token LETTER
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLETTER(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:641:5: ( '$' | 'A' .. 'Z' | 'a' .. 'z' | '_' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
    {
        if ( LA(1) == '$' || ((LA(1) >= 'A') && (LA(1) <= 'Z')) || LA(1) == '_' || ((LA(1) >= 'a') && (LA(1) <= 'z')) )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleLETTEREx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleLETTEREx; /* Prevent compiler warnings */
    ruleLETTEREx: ;

}
// $ANTLR end LETTER

//   Comes from: 647:5: ( '\\'' ( EscapeSequence |~ ( '\\'' | '\\\\' ) ) '\\'' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start CHARACTER_LITERAL
 *
 * Looks to match the characters the constitute the token CHARACTER_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCHARACTER_LITERAL(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = CHARACTER_LITERAL;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:647:5: ( '\\'' ( EscapeSequence |~ ( '\\'' | '\\\\' ) ) '\\'' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:647:9: '\\'' ( EscapeSequence |~ ( '\\'' | '\\\\' ) ) '\\''
    {
        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:647:14: ( EscapeSequence |~ ( '\\'' | '\\\\' ) )
        {
            int alt2=2;
            {
                int LA2_0 = LA(1);
                if ( (LA2_0 == '\\'))
                {
                    alt2=1;
                }
                else if ( (((LA2_0 >= 0x0000) && (LA2_0 <= '&')) || ((LA2_0 >= '(') && (LA2_0 <= '[')) || ((LA2_0 >= ']') && (LA2_0 <= 0xFFFF))))
                {
                    alt2=2;
                }
                else
                {

                    CONSTRUCTEX();
                    EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                    EXCEPTION->message      = (void *)"";
                    EXCEPTION->decisionNum  = 2;
                    EXCEPTION->state        = 0;


                    goto ruleCHARACTER_LITERALEx;

                }
            }
            switch (alt2)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:647:16: EscapeSequence
        	    {
        	        /* 647:16: EscapeSequence */
        	        mEscapeSequence(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCHARACTER_LITERALEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:647:33: ~ ( '\\'' | '\\\\' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '&')) || ((LA(1) >= '(') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleCHARACTER_LITERALEx;
        	        }


        	    }
        	    break;

            }
        }

        MATCHC('\'');
        if  (HASEXCEPTION())
        {
            goto ruleCHARACTER_LITERALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCHARACTER_LITERALEx; /* Prevent compiler warnings */
    ruleCHARACTER_LITERALEx: ;

}
// $ANTLR end CHARACTER_LITERAL

//   Comes from: 651:5: ( '\"' STRING_GUTS '\"' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_LITERAL
 *
 * Looks to match the characters the constitute the token STRING_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_LITERAL(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = STRING_LITERAL;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:651:5: ( '\"' STRING_GUTS '\"' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:651:8: '\"' STRING_GUTS '\"'
    {
        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


        /* 651:8: '\"' STRING_GUTS '\"' */
        mSTRING_GUTS(ctx );
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }



        MATCHC('"');
        if  (HASEXCEPTION())
        {
            goto ruleSTRING_LITERALEx;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleSTRING_LITERALEx; /* Prevent compiler warnings */
    ruleSTRING_LITERALEx: ;

}
// $ANTLR end STRING_LITERAL

//   Comes from: 657:5: ( ( EscapeSequence |~ ( '\\\\' | '\"' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start STRING_GUTS
 *
 * Looks to match the characters the constitute the token STRING_GUTS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mSTRING_GUTS(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:657:5: ( ( EscapeSequence |~ ( '\\\\' | '\"' ) )* )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:657:8: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*
    {
        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:657:8: ( EscapeSequence |~ ( '\\\\' | '\"' ) )*

        for (;;)
        {
            int alt3=3;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA3_0 = LA(1);
                if ( (LA3_0 == '\\'))
                {
                    alt3=1;
                }
                else if ( (((LA3_0 >= 0x0000) && (LA3_0 <= '!')) || ((LA3_0 >= '#') && (LA3_0 <= '[')) || ((LA3_0 >= ']') && (LA3_0 <= 0xFFFF))))
                {
                    alt3=2;
                }

            }
            switch (alt3)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:657:10: EscapeSequence
        	    {
        	        /* 657:10: EscapeSequence */
        	        mEscapeSequence(ctx );
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleSTRING_GUTSEx;
        	        }



        	    }
        	    break;
        	case 2:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:657:27: ~ ( '\\\\' | '\"' )
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '!')) || ((LA(1) >= '#') && (LA(1) <= '[')) || ((LA(1) >= ']') && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleSTRING_GUTSEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop3;	/* break out of the loop */
        	    break;
            }
        }
        loop3: ; /* Jump out to here if this rule does not match */


    }


    // This is where rules clean up and exit
    //
    goto ruleSTRING_GUTSEx; /* Prevent compiler warnings */
    ruleSTRING_GUTSEx: ;

}
// $ANTLR end STRING_GUTS

//   Comes from: 660:5: ( ( '-' )? ( '0' .. '9' )+ '..' ( '-' )? ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start RANGE_LITERAL
 *
 * Looks to match the characters the constitute the token RANGE_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mRANGE_LITERAL(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = RANGE_LITERAL;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:5: ( ( '-' )? ( '0' .. '9' )+ '..' ( '-' )? ( '0' .. '9' )+ )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:7: ( '-' )? ( '0' .. '9' )+ '..' ( '-' )? ( '0' .. '9' )+
    {
        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:7: ( '-' )?
        {
            int alt4=2;
            switch ( LA(1) )
            {
                case '-':
                	{
                		alt4=1;
                	}
                    break;
            }

            switch (alt4)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:8: '-'
        	    {
        	        MATCHC('-');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleRANGE_LITERALEx;
        	        }


        	    }
        	    break;

            }
        }

        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:14: ( '0' .. '9' )+
        {
            int cnt5=0;

            for (;;)
            {
                int alt5=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt5=1;
        		}
        	    break;

        	}

        	switch (alt5)
        	{
        	    case 1:
        	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleRANGE_LITERALEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt5 >= 1 )
        		{
        		    goto loop5;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleRANGE_LITERALEx;
        	}
        	cnt5++;
            }
            loop5: ;	/* Jump to here if this rule does not match */
        }

        MATCHS(lit_3);
        if  (HASEXCEPTION())
        {
            goto ruleRANGE_LITERALEx;
        }




        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:31: ( '-' )?
        {
            int alt6=2;
            switch ( LA(1) )
            {
                case '-':
                	{
                		alt6=1;
                	}
                    break;
            }

            switch (alt6)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:32: '-'
        	    {
        	        MATCHC('-');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleRANGE_LITERALEx;
        	        }


        	    }
        	    break;

            }
        }

        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:660:37: ( '0' .. '9' )+
        {
            int cnt7=0;

            for (;;)
            {
                int alt7=2;
        	switch ( LA(1) )
        	{
        	case '0':
        	case '1':
        	case '2':
        	case '3':
        	case '4':
        	case '5':
        	case '6':
        	case '7':
        	case '8':
        	case '9':
        		{
        			alt7=1;
        		}
        	    break;

        	}

        	switch (alt7)
        	{
        	    case 1:
        	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
        	        {
        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	            {
        	                CONSUME();
        	            }
        	            else
        	            {
        	                CONSTRUCTEX();
        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	                LRECOVER();
        	                goto ruleRANGE_LITERALEx;
        	            }


        	        }
        	        break;

        	    default:

        		if ( cnt7 >= 1 )
        		{
        		    goto loop7;
        		}
        		/* mismatchedSetEx()
        		 */
        		CONSTRUCTEX();
        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


        		goto ruleRANGE_LITERALEx;
        	}
        	cnt7++;
            }
            loop7: ;	/* Jump to here if this rule does not match */
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleRANGE_LITERALEx; /* Prevent compiler warnings */
    ruleRANGE_LITERALEx: ;

}
// $ANTLR end RANGE_LITERAL

//   Comes from: 664:5: ( ( '0' | ( '-' )? '1' .. '9' ( '0' .. '9' )* ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start DECIMAL_LITERAL
 *
 * Looks to match the characters the constitute the token DECIMAL_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mDECIMAL_LITERAL(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = DECIMAL_LITERAL;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:5: ( ( '0' | ( '-' )? '1' .. '9' ( '0' .. '9' )* ) )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:7: ( '0' | ( '-' )? '1' .. '9' ( '0' .. '9' )* )
    {
        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:7: ( '0' | ( '-' )? '1' .. '9' ( '0' .. '9' )* )
        {
            int alt10=2;
            switch ( LA(1) )
            {
            case '0':
            	{
            		alt10=1;
            	}
                break;
            case '-':
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            	{
            		alt10=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 10;
                EXCEPTION->state        = 0;


                goto ruleDECIMAL_LITERALEx;

            }

            switch (alt10)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:8: '0'
        	    {
        	        MATCHC('0');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleDECIMAL_LITERALEx;
        	        }


        	    }
        	    break;
        	case 2:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:14: ( '-' )? '1' .. '9' ( '0' .. '9' )*
        	    {
        	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:14: ( '-' )?
        	        {
        	            int alt8=2;
        	            switch ( LA(1) )
        	            {
        	                case '-':
        	                	{
        	                		alt8=1;
        	                	}
        	                    break;
        	            }

        	            switch (alt8)
        	            {
        	        	case 1:
        	        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:15: '-'
        	        	    {
        	        	        MATCHC('-');
        	        	        if  (HASEXCEPTION())
        	        	        {
        	        	            goto ruleDECIMAL_LITERALEx;
        	        	        }


        	        	    }
        	        	    break;

        	            }
        	        }

        	        MATCHRANGE('1', '9');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleDECIMAL_LITERALEx;
        	        }


        	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:664:30: ( '0' .. '9' )*

        	        for (;;)
        	        {
        	            int alt9=2;
        	            switch ( LA(1) )
        	            {
        	            case '0':
        	            case '1':
        	            case '2':
        	            case '3':
        	            case '4':
        	            case '5':
        	            case '6':
        	            case '7':
        	            case '8':
        	            case '9':
        	            	{
        	            		alt9=1;
        	            	}
        	                break;

        	            }

        	            switch (alt9)
        	            {
        	        	case 1:
        	        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
        	        	    {
        	        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
        	        	        {
        	        	            CONSUME();
        	        	        }
        	        	        else
        	        	        {
        	        	            CONSTRUCTEX();
        	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	        	            LRECOVER();
        	        	            goto ruleDECIMAL_LITERALEx;
        	        	        }


        	        	    }
        	        	    break;

        	        	default:
        	        	    goto loop9;	/* break out of the loop */
        	        	    break;
        	            }
        	        }
        	        loop9: ; /* Jump out to here if this rule does not match */


        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleDECIMAL_LITERALEx; /* Prevent compiler warnings */
    ruleDECIMAL_LITERALEx: ;

}
// $ANTLR end DECIMAL_LITERAL

//   Comes from: 668:5: ( ( '-' )? ( '0' .. '9' )+ '.' ( '0' .. '9' )* | '.' ( '0' .. '9' )+ )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start FLOATING_POINT_LITERAL
 *
 * Looks to match the characters the constitute the token FLOATING_POINT_LITERAL
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mFLOATING_POINT_LITERAL(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = FLOATING_POINT_LITERAL;


    {
        //  /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:668:5: ( ( '-' )? ( '0' .. '9' )+ '.' ( '0' .. '9' )* | '.' ( '0' .. '9' )+ )

        ANTLR3_UINT32 alt15;

        alt15=2;

        switch ( LA(1) )
        {
        case '-':
        case '0':
        case '1':
        case '2':
        case '3':
        case '4':
        case '5':
        case '6':
        case '7':
        case '8':
        case '9':
        	{
        		alt15=1;
        	}
            break;
        case '.':
        	{
        		alt15=2;
        	}
            break;

        default:
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
            EXCEPTION->message      = (void *)"";
            EXCEPTION->decisionNum  = 15;
            EXCEPTION->state        = 0;


            goto ruleFLOATING_POINT_LITERALEx;

        }

        switch (alt15)
        {
    	case 1:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:668:9: ( '-' )? ( '0' .. '9' )+ '.' ( '0' .. '9' )*
    	    {
    	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:668:9: ( '-' )?
    	        {
    	            int alt11=2;
    	            switch ( LA(1) )
    	            {
    	                case '-':
    	                	{
    	                		alt11=1;
    	                	}
    	                    break;
    	            }

    	            switch (alt11)
    	            {
    	        	case 1:
    	        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:668:10: '-'
    	        	    {
    	        	        MATCHC('-');
    	        	        if  (HASEXCEPTION())
    	        	        {
    	        	            goto ruleFLOATING_POINT_LITERALEx;
    	        	        }


    	        	    }
    	        	    break;

    	            }
    	        }

    	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:668:15: ( '0' .. '9' )+
    	        {
    	            int cnt12=0;

    	            for (;;)
    	            {
    	                int alt12=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt12=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt12)
    	        	{
    	        	    case 1:
    	        	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleFLOATING_POINT_LITERALEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt12 >= 1 )
    	        		{
    	        		    goto loop12;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleFLOATING_POINT_LITERALEx;
    	        	}
    	        	cnt12++;
    	            }
    	            loop12: ;	/* Jump to here if this rule does not match */
    	        }

    	        MATCHC('.');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleFLOATING_POINT_LITERALEx;
    	        }


    	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:668:31: ( '0' .. '9' )*

    	        for (;;)
    	        {
    	            int alt13=2;
    	            switch ( LA(1) )
    	            {
    	            case '0':
    	            case '1':
    	            case '2':
    	            case '3':
    	            case '4':
    	            case '5':
    	            case '6':
    	            case '7':
    	            case '8':
    	            case '9':
    	            	{
    	            		alt13=1;
    	            	}
    	                break;

    	            }

    	            switch (alt13)
    	            {
    	        	case 1:
    	        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
    	        	    {
    	        	        if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	        {
    	        	            CONSUME();
    	        	        }
    	        	        else
    	        	        {
    	        	            CONSTRUCTEX();
    	        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	            LRECOVER();
    	        	            goto ruleFLOATING_POINT_LITERALEx;
    	        	        }


    	        	    }
    	        	    break;

    	        	default:
    	        	    goto loop13;	/* break out of the loop */
    	        	    break;
    	            }
    	        }
    	        loop13: ; /* Jump out to here if this rule does not match */


    	    }
    	    break;
    	case 2:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:669:9: '.' ( '0' .. '9' )+
    	    {
    	        MATCHC('.');
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleFLOATING_POINT_LITERALEx;
    	        }


    	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:669:13: ( '0' .. '9' )+
    	        {
    	            int cnt14=0;

    	            for (;;)
    	            {
    	                int alt14=2;
    	        	switch ( LA(1) )
    	        	{
    	        	case '0':
    	        	case '1':
    	        	case '2':
    	        	case '3':
    	        	case '4':
    	        	case '5':
    	        	case '6':
    	        	case '7':
    	        	case '8':
    	        	case '9':
    	        		{
    	        			alt14=1;
    	        		}
    	        	    break;

    	        	}

    	        	switch (alt14)
    	        	{
    	        	    case 1:
    	        	        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
    	        	        {
    	        	            if ( ((LA(1) >= '0') && (LA(1) <= '9')) )
    	        	            {
    	        	                CONSUME();
    	        	            }
    	        	            else
    	        	            {
    	        	                CONSTRUCTEX();
    	        	                EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
    	        	                EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

    	        	                LRECOVER();
    	        	                goto ruleFLOATING_POINT_LITERALEx;
    	        	            }


    	        	        }
    	        	        break;

    	        	    default:

    	        		if ( cnt14 >= 1 )
    	        		{
    	        		    goto loop14;
    	        		}
    	        		/* mismatchedSetEx()
    	        		 */
    	        		CONSTRUCTEX();
    	        		EXCEPTION->type = ANTLR3_EARLY_EXIT_EXCEPTION;
    	        		EXCEPTION->name = (void *)ANTLR3_EARLY_EXIT_NAME;


    	        		goto ruleFLOATING_POINT_LITERALEx;
    	        	}
    	        	cnt14++;
    	            }
    	            loop14: ;	/* Jump to here if this rule does not match */
    	        }

    	    }
    	    break;

        }
    }
	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleFLOATING_POINT_LITERALEx; /* Prevent compiler warnings */
    ruleFLOATING_POINT_LITERALEx: ;

}
// $ANTLR end FLOATING_POINT_LITERAL

//   Comes from: 676:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start EscapeSequence
 *
 * Looks to match the characters the constitute the token EscapeSequence
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mEscapeSequence(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:676:5: ( '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' ) )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:676:9: '\\\\' ( 'b' | 't' | 'n' | 'f' | 'r' | '\\\"' | '\\'' | '\\\\' )
    {
        MATCHC('\\');
        if  (HASEXCEPTION())
        {
            goto ruleEscapeSequenceEx;
        }


        if ( LA(1) == '"' || LA(1) == '\'' || LA(1) == '\\' || LA(1) == 'b' || LA(1) == 'f' || LA(1) == 'n' || LA(1) == 'r' || LA(1) == 't' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleEscapeSequenceEx;
        }


    }


    // This is where rules clean up and exit
    //
    goto ruleEscapeSequenceEx; /* Prevent compiler warnings */
    ruleEscapeSequenceEx: ;

}
// $ANTLR end EscapeSequence

//   Comes from: 679:5: ( '/*' ( options {greedy=false; } : . )* '*/' )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start COMMENT
 *
 * Looks to match the characters the constitute the token COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mCOMMENT(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = COMMENT;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:679:5: ( '/*' ( options {greedy=false; } : . )* '*/' )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:679:9: '/*' ( options {greedy=false; } : . )* '*/'
    {
        MATCHS(lit_4);
        if  (HASEXCEPTION())
        {
            goto ruleCOMMENTEx;
        }




        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:679:14: ( options {greedy=false; } : . )*

        for (;;)
        {
            int alt16=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA16_0 = LA(1);
                if ( (LA16_0 == '*'))
                {
                    {
                       /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                        */
                        int LA16_1 = LA(2);
                        if ( (LA16_1 == '/'))
                        {
                            alt16=2;
                        }
                        else if ( (((LA16_1 >= 0x0000) && (LA16_1 <= '.')) || ((LA16_1 >= '0') && (LA16_1 <= 0xFFFF))))
                        {
                            alt16=1;
                        }

                    }
                }
                else if ( (((LA16_0 >= 0x0000) && (LA16_0 <= ')')) || ((LA16_0 >= '+') && (LA16_0 <= 0xFFFF))))
                {
                    alt16=1;
                }

            }
            switch (alt16)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:679:42: .
        	    {
        	        MATCHANY();
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleCOMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop16;	/* break out of the loop */
        	    break;
            }
        }
        loop16: ; /* Jump out to here if this rule does not match */


        MATCHS(lit_5);
        if  (HASEXCEPTION())
        {
            goto ruleCOMMENTEx;
        }




        {
            LEXSTATE->channel=HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleCOMMENTEx; /* Prevent compiler warnings */
    ruleCOMMENTEx: ;

}
// $ANTLR end COMMENT

//   Comes from: 683:5: ( '//' (~ ( '\\n' | '\\r' ) )* )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start LINE_COMMENT
 *
 * Looks to match the characters the constitute the token LINE_COMMENT
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mLINE_COMMENT(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = LINE_COMMENT;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:683:5: ( '//' (~ ( '\\n' | '\\r' ) )* )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:683:7: '//' (~ ( '\\n' | '\\r' ) )*
    {
        MATCHS(lit_6);
        if  (HASEXCEPTION())
        {
            goto ruleLINE_COMMENTEx;
        }




        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:683:12: (~ ( '\\n' | '\\r' ) )*

        for (;;)
        {
            int alt17=2;
            {
               /* dfaLoopbackState(k,edges,eotPredictsAlt,description,stateNumber,semPredState)
                */
                int LA17_0 = LA(1);
                if ( (((LA17_0 >= 0x0000) && (LA17_0 <= '\t')) || ((LA17_0 >= 0x000B) && (LA17_0 <= '\f')) || ((LA17_0 >= 0x000E) && (LA17_0 <= 0xFFFF))))
                {
                    alt17=1;
                }

            }
            switch (alt17)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:
        	    {
        	        if ( ((LA(1) >= 0x0000) && (LA(1) <= '\t')) || ((LA(1) >= 0x000B) && (LA(1) <= '\f')) || ((LA(1) >= 0x000E) && (LA(1) <= 0xFFFF)) )
        	        {
        	            CONSUME();
        	        }
        	        else
        	        {
        	            CONSTRUCTEX();
        	            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
        	            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

        	            LRECOVER();
        	            goto ruleLINE_COMMENTEx;
        	        }


        	    }
        	    break;

        	default:
        	    goto loop17;	/* break out of the loop */
        	    break;
            }
        }
        loop17: ; /* Jump out to here if this rule does not match */


        {
            LEXSTATE->channel=HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleLINE_COMMENTEx; /* Prevent compiler warnings */
    ruleLINE_COMMENTEx: ;

}
// $ANTLR end LINE_COMMENT

//   Comes from: 686:8: ( ( '\\r\\n' | '\\n' | '\\r' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start NEWLINE
 *
 * Looks to match the characters the constitute the token NEWLINE
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mNEWLINE(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = NEWLINE;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:686:8: ( ( '\\r\\n' | '\\n' | '\\r' ) )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:686:10: ( '\\r\\n' | '\\n' | '\\r' )
    {
        // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:686:10: ( '\\r\\n' | '\\n' | '\\r' )
        {
            int alt18=3;
            switch ( LA(1) )
            {
            case '\r':
            	{
            		switch ( LA(2) )
            		{
            		case '\n':
            			{
            				alt18=1;
            			}
            		    break;

            		default:
            		    alt18=3;
            		}

            	}
                break;
            case '\n':
            	{
            		alt18=2;
            	}
                break;

            default:
                CONSTRUCTEX();
                EXCEPTION->type         = ANTLR3_NO_VIABLE_ALT_EXCEPTION;
                EXCEPTION->message      = (void *)"";
                EXCEPTION->decisionNum  = 18;
                EXCEPTION->state        = 0;


                goto ruleNEWLINEEx;

            }

            switch (alt18)
            {
        	case 1:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:686:11: '\\r\\n'
        	    {
        	        MATCHS(lit_7);
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleNEWLINEEx;
        	        }




        	    }
        	    break;
        	case 2:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:686:18: '\\n'
        	    {
        	        MATCHC('\n');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleNEWLINEEx;
        	        }


        	    }
        	    break;
        	case 3:
        	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:686:23: '\\r'
        	    {
        	        MATCHC('\r');
        	        if  (HASEXCEPTION())
        	        {
        	            goto ruleNEWLINEEx;
        	        }


        	    }
        	    break;

            }
        }

    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleNEWLINEEx; /* Prevent compiler warnings */
    ruleNEWLINEEx: ;

}
// $ANTLR end NEWLINE

//   Comes from: 688:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
/** \brief Lexer rule generated by ANTLR3
 *
 * $ANTLR start WS
 *
 * Looks to match the characters the constitute the token WS
 * from the attached input stream.
 *
 *
 * \remark
 *  - lexer->error == ANTLR3_TRUE if an exception was thrown.
 */
static ANTLR3_INLINE
void mWS(ppqlLexer ctx)
{
	ANTLR3_UINT32	_type;

    _type	    = WS;


    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:688:5: ( ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' ) )
    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:688:8: ( ' ' | '\\r' | '\\t' | '\\u000C' | '\\n' )
    {
        if ( ((LA(1) >= '\t') && (LA(1) <= '\n')) || ((LA(1) >= '\f') && (LA(1) <= '\r')) || LA(1) == ' ' )
        {
            CONSUME();
        }
        else
        {
            CONSTRUCTEX();
            EXCEPTION->type         = ANTLR3_MISMATCHED_SET_EXCEPTION;
            EXCEPTION->name         = (void *)ANTLR3_MISMATCHED_SET_NAME;

            LRECOVER();
            goto ruleWSEx;
        }


        {
            LEXSTATE->channel=HIDDEN;
        }


    }

	LEXSTATE->type = _type;
    // This is where rules clean up and exit
    //
    goto ruleWSEx; /* Prevent compiler warnings */
    ruleWSEx: ;

}
// $ANTLR end WS

/** This is the entry point in to the lexer from an object that
 *  wants to generate the next token, such as a pCOMMON_TOKEN_STREAM
 */
static void
mTokens(ppqlLexer ctx)
{
    {
        //  /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:8: ( T__17 | T__18 | T__19 | T__20 | T__21 | T__22 | T__23 | T__24 | T__25 | T__26 | T__27 | T__28 | T__29 | T__30 | IDENTIFIER | CHARACTER_LITERAL | STRING_LITERAL | RANGE_LITERAL | DECIMAL_LITERAL | FLOATING_POINT_LITERAL | COMMENT | LINE_COMMENT | NEWLINE | WS )

        ANTLR3_UINT32 alt19;

        alt19=24;

        alt19 = cdfa19.predict(ctx, RECOGNIZER, ISTREAM, &cdfa19);
        if  (HASEXCEPTION())
        {
            goto ruleTokensEx;
        }

        switch (alt19)
        {
    	case 1:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:10: T__17
    	    {
    	        /* 1:10: T__17 */
    	        mT__17(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 2:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:16: T__18
    	    {
    	        /* 1:16: T__18 */
    	        mT__18(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 3:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:22: T__19
    	    {
    	        /* 1:22: T__19 */
    	        mT__19(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 4:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:28: T__20
    	    {
    	        /* 1:28: T__20 */
    	        mT__20(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 5:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:34: T__21
    	    {
    	        /* 1:34: T__21 */
    	        mT__21(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 6:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:40: T__22
    	    {
    	        /* 1:40: T__22 */
    	        mT__22(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 7:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:46: T__23
    	    {
    	        /* 1:46: T__23 */
    	        mT__23(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 8:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:52: T__24
    	    {
    	        /* 1:52: T__24 */
    	        mT__24(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 9:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:58: T__25
    	    {
    	        /* 1:58: T__25 */
    	        mT__25(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 10:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:64: T__26
    	    {
    	        /* 1:64: T__26 */
    	        mT__26(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 11:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:70: T__27
    	    {
    	        /* 1:70: T__27 */
    	        mT__27(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 12:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:76: T__28
    	    {
    	        /* 1:76: T__28 */
    	        mT__28(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 13:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:82: T__29
    	    {
    	        /* 1:82: T__29 */
    	        mT__29(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 14:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:88: T__30
    	    {
    	        /* 1:88: T__30 */
    	        mT__30(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 15:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:94: IDENTIFIER
    	    {
    	        /* 1:94: IDENTIFIER */
    	        mIDENTIFIER(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 16:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:105: CHARACTER_LITERAL
    	    {
    	        /* 1:105: CHARACTER_LITERAL */
    	        mCHARACTER_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 17:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:123: STRING_LITERAL
    	    {
    	        /* 1:123: STRING_LITERAL */
    	        mSTRING_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 18:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:138: RANGE_LITERAL
    	    {
    	        /* 1:138: RANGE_LITERAL */
    	        mRANGE_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 19:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:152: DECIMAL_LITERAL
    	    {
    	        /* 1:152: DECIMAL_LITERAL */
    	        mDECIMAL_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 20:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:168: FLOATING_POINT_LITERAL
    	    {
    	        /* 1:168: FLOATING_POINT_LITERAL */
    	        mFLOATING_POINT_LITERAL(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 21:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:191: COMMENT
    	    {
    	        /* 1:191: COMMENT */
    	        mCOMMENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 22:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:199: LINE_COMMENT
    	    {
    	        /* 1:199: LINE_COMMENT */
    	        mLINE_COMMENT(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 23:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:212: NEWLINE
    	    {
    	        /* 1:212: NEWLINE */
    	        mNEWLINE(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;
    	case 24:
    	    // /home/jaholtz/Treehouse-Private/TreeHouse/pql.g:1:220: WS
    	    {
    	        /* 1:220: WS */
    	        mWS(ctx );
    	        if  (HASEXCEPTION())
    	        {
    	            goto ruleTokensEx;
    	        }



    	    }
    	    break;

        }
    }


    goto ruleTokensEx; /* Prevent compiler warnings */
ruleTokensEx: ;
}

/* =========================================================================
 * Lexer matching rules end.
 * =========================================================================
 */
/* End of Lexer code
 * ================================================
 * ================================================
 */


/* End of code
 * =============================================================================
 */
