/** \file
 *  This C header file was generated by $ANTLR version 3.4
 *
 *     -  From the grammar source file : /home/jaholtz/Treehouse-Private/TreeHouse/pql.g
 *     -                            On : 2013-07-23 15:55:33
 *     -                for the parser : pqlParserParser
 *
 * Editing it, at least manually, is not wise.
 *
 * C language generator and runtime by Jim Idle, jimi|hereisanat|idle|dotgoeshere|ws.
 *
 *
 * The parser 
pqlParser

has the callable functions (rules) shown below,
 * which will invoke the code for the associated rule in the source grammar
 * assuming that the input stream is pointing to a token/text stream that could begin
 * this rule.
 *
 * For instance if you call the first (topmost) rule in a parser grammar, you will
 * get the results of a full parse, but calling a rule half way through the grammar will
 * allow you to pass part of a full token stream to the parser, such as for syntax checking
 * in editors and so on.
 *
 * The parser entry points are called indirectly (by function pointer to function) via
 * a parser context typedef ppqlParser, which is returned from a call to pqlParserNew().
 *
 * The methods in ppqlParser are  as follows:
 *
 *  - 
 void
      ppqlParser->prog(ppqlParser)
 *  - 
 void
      ppqlParser->query(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->assignment_expression(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->not_expression(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->difference_expression(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->union_expression(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->intersection_expression(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->equality_expression(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->postfix_expression(ppqlParser)
 *  - 
 vector<pqlsymbol * >
      ppqlParser->argument_expression_list(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->primary_expression(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->constant_expression_list(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->atom(ppqlParser)
 *  - 
 pqlsymbol *
      ppqlParser->constant(ppqlParser)
 *
 * The return type for any particular rule is of course determined by the source
 * grammar file.
 */
// [The "BSD license"]
// Copyright (c) 2005-2009 Jim Idle, Temporal Wave LLC
// http://www.temporal-wave.com
// http://www.linkedin.com/in/jimidle
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions
// are met:
// 1. Redistributions of source code must retain the above copyright
//    notice, this list of conditions and the following disclaimer.
// 2. Redistributions in binary form must reproduce the above copyright
//    notice, this list of conditions and the following disclaimer in the
//    documentation and/or other materials provided with the distribution.
// 3. The name of the author may not be used to endorse or promote products
//    derived from this software without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
// IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
// OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
// IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT,
// INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
// NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
// DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
// THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
// THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef	_pqlParser_H
#define _pqlParser_H
/* =============================================================================
 * Standard antlr3 C runtime definitions
 */
#include    <antlr3.h>

/* End of standard antlr 3 runtime definitions
 * =============================================================================
 */

  #include <iostream> 
  #include <string>
  #include <vector>
  #include <sstream>
  #include <set>
  #include <algorithm>
  #include <memory>	  
  
  //#include "HashTableSearch.h"
  #include "UtilityFunctions.h"
  #include "UserFunctions.h"
  #include "label-map.hh"
  #include "global.h"
  #include "pqlsymbol.h"
  #include "THGlobals.h"
  using namespace std;


#ifdef __cplusplus
extern "C" {
#endif

// Forward declare the context typedef so that we can use it before it is
// properly defined. Delegators and delegates (from import statements) are
// interdependent and their context structures contain pointers to each other
// C only allows such things to be declared if you pre-declare the typedef.
//
typedef struct pqlParser_Ctx_struct pqlParser, * ppqlParser;



#ifdef	ANTLR3_WINDOWS
// Disable: Unreferenced parameter,							- Rules with parameters that are not used
//          constant conditional,							- ANTLR realizes that a prediction is always true (synpred usually)
//          initialized but unused variable					- tree rewrite variables declared but not needed
//          Unreferenced local variable						- lexer rule declares but does not always use _type
//          potentially unitialized variable used			- retval always returned from a rule
//			unreferenced local function has been removed	- susually getTokenNames or freeScope, they can go without warnigns
//
// These are only really displayed at warning level /W4 but that is the code ideal I am aiming at
// and the codegen must generate some of these warnings by necessity, apart from 4100, which is
// usually generated when a parser rule is given a parameter that it does not use. Mostly though
// this is a matter of orthogonality hence I disable that one.
//
#pragma warning( disable : 4100 )
#pragma warning( disable : 4101 )
#pragma warning( disable : 4127 )
#pragma warning( disable : 4189 )
#pragma warning( disable : 4505 )
#pragma warning( disable : 4701 )
#endif

/** Context tracking structure for 
pqlParser

 */
struct pqlParser_Ctx_struct
{
    /** Built in ANTLR3 context tracker contains all the generic elements
     *  required for context tracking.
     */
    pANTLR3_PARSER   pParser;

     void
     (*prog)	(struct pqlParser_Ctx_struct * ctx);

     void
     (*query)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*assignment_expression)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*not_expression)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*difference_expression)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*union_expression)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*intersection_expression)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*equality_expression)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*postfix_expression)	(struct pqlParser_Ctx_struct * ctx);

     vector<pqlsymbol * >
     (*argument_expression_list)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*primary_expression)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*constant_expression_list)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*atom)	(struct pqlParser_Ctx_struct * ctx);

     pqlsymbol *
     (*constant)	(struct pqlParser_Ctx_struct * ctx);
    // Delegated rules

    const char * (*getGrammarFileName)();
    void            (*reset)  (struct pqlParser_Ctx_struct * ctx);
    void	    (*free)   (struct pqlParser_Ctx_struct * ctx);
};

// Function protoypes for the constructor functions that external translation units
// such as delegators and delegates may wish to call.
//
ANTLR3_API ppqlParser pqlParserNew         (
pANTLR3_COMMON_TOKEN_STREAM
 instream);
ANTLR3_API ppqlParser pqlParserNewSSD      (
pANTLR3_COMMON_TOKEN_STREAM
 instream, pANTLR3_RECOGNIZER_SHARED_STATE state);

/** Symbolic definitions of all the tokens that the 
parser
 will work with.
 * \{
 *
 * Antlr will define EOF, but we can't use that as it it is too common in
 * in C header files and that would be confusing. There is no way to filter this out at the moment
 * so we just undef it here for now. That isn't the value we get back from C recognizers
 * anyway. We are looking for ANTLR3_TOKEN_EOF.
 */
#ifdef	EOF
#undef	EOF
#endif
#ifdef	Tokens
#undef	Tokens
#endif
#define EOF      -1
#define T__17      17
#define T__18      18
#define T__19      19
#define T__20      20
#define T__21      21
#define T__22      22
#define T__23      23
#define T__24      24
#define T__25      25
#define T__26      26
#define T__27      27
#define T__28      28
#define T__29      29
#define T__30      30
#define CHARACTER_LITERAL      4
#define COMMENT      5
#define DECIMAL_LITERAL      6
#define EscapeSequence      7
#define FLOATING_POINT_LITERAL      8
#define IDENTIFIER      9
#define LETTER      10
#define LINE_COMMENT      11
#define NEWLINE      12
#define RANGE_LITERAL      13
#define STRING_GUTS      14
#define STRING_LITERAL      15
#define WS      16
#ifdef	EOF
#undef	EOF
#define	EOF	ANTLR3_TOKEN_EOF
#endif

#ifndef TOKENSOURCE
#define TOKENSOURCE(lxr) lxr->pLexer->rec->state->tokSource
#endif

/* End of token definitions for pqlParser
 * =============================================================================
 */
/** } */

#ifdef __cplusplus
}
#endif

#endif

/* END - Note:Keep extra line feed to satisfy UNIX systems */
